### ISSUE TITLE
问一下楼主的ui资源是怎么获取的？

### ISSUE THREAD

**Issue by qianlongdoit** [heyushuo/mpvue-shop#3]
我也想自己撸一个小程序，但是苦于UI资源不知道如何去获取
不知道你是怎么获取到严选的图片和颜色资源的呢？

**Comment by heyushuo** [comment]
ui资源大部分小图标都是使用严选的线上图片地址,整体的列表还是商品,商品详情是一个网友的sql数据,那个网友应该也是爬取的

**Comment by qianlongdoit** [comment]
好的，谢谢了
